@{
	# Script module or binary module file associated with this manifest
	ModuleToProcess = 'HPOneView.420.psm1'
	
	# Version number of this module.
	ModuleVersion = '4.20.1971.1960'
	
	# ID used to uniquely identify this module
	GUID = 'bc3d2154-14be-450c-a9de-29d8bab837a8'
	
	# Author of this module
	Author = 'Hewlett-Packard Enterprise'
	
	# Company or vendor of this module
	CompanyName = 'Hewlett-Packard Enterprise'
	
	# Copyright statement for this module
	Copyright = 'Copyright (c) 2019 Hewlett-Packard Enterprise'
	
	# Description of the functionality provided by this module
	Description = 'HPE OneView PowerShell Library'
	
	# Minimum version of the Windows PowerShell engine required by this module
	PowerShellVersion = '4.0'
	
	# Modules that must be imported into the global environment prior to importing
	# this module
	RequiredModules = @(
		@{ ModuleName = 'PSFramework'; ModuleVersion = '1.0.13' }
		@{ ModuleName = 'FormatPX'; ModuleVersion = '1.1.3.15' },
		@{ ModuleName = 'SnippetPX'; ModuleVersion = '1.0.5.18' }
	)
	
	# Assemblies that must be loaded prior to importing this module
	RequiredAssemblies = @(
		'bin\HPOneView_Classes.420.dll'
		'bin\SysadminsLV.Asn1Parser.dll'
		# 'bin\HPOneView.420.dll'
	)
	
	# Type files (.ps1xml) to be loaded when importing this module
	# TypesToProcess = @('xml\HPOneView.420.Types.ps1xml')
	
	# Format files (.ps1xml) to be loaded when importing this module
	FormatsToProcess   = @(
		#'xml\HPOneView.420.Format.ps1xml'
		'xml\Appliance.format.ps1xml'
		'xml\Cluster.format.ps1xml'
		'xml\Networking.format.ps1xml'
		'xml\Server.format.ps1xml'
		'xml\Storage.format.ps1xml'
	)
	
	# Functions to export from this module
	FunctionsToExport  = @(
		'Add-HPOVApplianceTrustedCertificate'
		'Add-HPOVBaseline'
		'Add-HPOVClusterNodeToCluster'
		'Add-HPOVEnclosure'
		'Add-HPOVFabricManager'
		'Add-HPOVHypervisorManager'
		'Add-HPOVLdapServer'
		'Add-HPOVPowerDevice'
		'Add-HPOVRackManager'
		'Add-HPOVRackToDataCenter'
		'Add-HPOVRemoteFrame'
		'Add-HPOVResourceToLabel'
		'Add-HPOVResourceToRack'
		'Add-HPOVResourceToScope'
		'Add-HPOVSanManager'
		'Add-HPOVServer'
		'Add-HPOVSmtpAlertEmailFilter'
		'Add-HPOVStoragePool'
		'Add-HPOVStorageSystem'
		'Add-HPOVStorageVolume'
		'Clear-HPOVAlert'
		'Connect-HPOVMgmt'
		'Convert-HPOVServerProfile'
		'Convert-HPOVServerProfileTemplate'
		'ConvertTo-HPOVImageStreamerConfiguration'
		'ConvertTo-HPOVPowerShellScript'
		'ConvertTo-HPOVServerProfileTemplate'
		'ConvertTo-HPOVStorageVolume'
		'Copy-HPOVServerProfile'
		'Disable-HPOVApplianceComplexPasswords'
		'Disable-HPOVApplianceServiceConsoleAccess'
		'Disable-HPOVApplianceSshAccess'
		'Disable-HPOVApplianceTwoFactorAuthentication'
		'Disable-HPOVCertificateValidation'
		'Disable-HPOVDebug'
		'Disable-HPOVDeviceUid'
		'Disable-HPOVLdapLocalLogin'
		'Disable-HPOVLogicalInterconnectPortMonitoring'
		'Disable-HPOVMSDSC'
		'Disable-HPOVRemoteSupport'
		'Disable-HPOVRemoteSyslog'
		'Disconnect-HPOVMgmt'
		'Enable-HPOVApplianceComplexPasswords'
		'Enable-HPOVApplianceServiceConsoleAccess'
		'Enable-HPOVApplianceSshAccess'
		'Enable-HPOVCertificateValidation'
		'Enable-HPOVComposerHANode'
		'Enable-HPOVDebug'
		'Enable-HPOVDeviceUid'
		'Enable-HPOVLdapLocalLogin'
		'Enable-HPOVLogicalInterconnectPortMonitoring'
		'Enable-HPOVMSDSC'
		'Enable-HPOVRemoteSupport'
		'Enable-HPOVRemoteSyslog'
		'Get-HPOVAddressPool'
		'Get-HPOVAddressPoolRange'
		'Get-HPOVAddressPoolSubnet'
		'Get-HPOVAlert'
		'Get-HPOVApplianceAvailableSecurityMode'
		'Get-HPOVApplianceCertificateStatus'
		'Get-HPOVApplianceCurrentSecurityMode'
		'Get-HPOVApplianceDateTime'
		'Get-HPOVApplianceGlobalSetting'
		'Get-HPOVApplianceNetworkConfig'
		'Get-HPOVApplianceProxy'
		'Get-HPOVApplianceSecurityProtocol'
		'Get-HPOVApplianceSnmpV3EngineId'
		'Get-HPOVApplianceTrapDestination'
		'Get-HPOVApplianceTrustedCertificate'
		'Get-HPOVApplianceTwoFactorAuthentication'
		'Get-HPOVAuditLog'
		'Get-HPOVAuditLogArchive'
		'Get-HPOVAutomaticBackupConfig'
		'Get-HPOVAvailableDriveType'
		'Get-HPOVBackup'
		'Get-HPOVBaseline'
		'Get-HPOVBaselineRepository'
		'Get-HPOVClusterNode'
		'Get-HPOVClusterProfile'
		'Get-HPOVCommandTrace'
		'Get-HPOVComposerNode'
		'Get-HPOVDatacenter'
		'Get-HPOVDriveEnclosure'
		'Get-HPOVEnclosure'
		'Get-HPOVEnclosureGroup'
		'Get-HPOVEulaStatus'
		'Get-HPOVFabricManager'
		'Get-HPOVHealthStatus'
		'Get-HPOVHypervisorManager'
		'Get-HPOVIloSso'
		'Get-HPOVImageStreamerAppliance'
		'Get-HPOVInterconnect'
		'Get-HPOVInterconnectType'
		'Get-HPOVLabel'
		'Get-HPOVLdap'
		'Get-HPOVLdapDirectory'
		'Get-HPOVLdapGroup'
		'Get-HPOVLicense'
		'Get-HPOVLogicalEnclosure'
		'Get-HPOVLogicalInterconnect'
		'Get-HPOVLogicalInterconnectGroup'
		'Get-HPOVLogicalInterconnectPortMonitoring'
		'Get-HPOVLogicalSwitch'
		'Get-HPOVLogicalSwitchGroup'
		'Get-HPOVLoginMessage'
		'Get-HPOVManagedSan'
		'Get-HPOVNetwork'
		'Get-HPOVNetworkSet'
		'Get-HPOVOSDeploymentPlan'
		'Get-HPOVOSDeploymentPlanAttribute'
		'Get-HPOVOSDeploymentServer'
		'Get-HPOVPEndingUpdate'
		'Get-HPOVPowerDevice'
		'Get-HPOVPowerPotentialDeviceConnection'
		'Get-HPOVRack'
		'Get-HPOVRackManager'
		'Get-HPOVRackMember'
		'Get-HPOVRemoteSupport'
		'Get-HPOVRemoteSupportContact'
		'Get-HPOVRemoteSupportDataCollectionSchedule'
		'Get-HPOVRemoteSupportDefaultSite'
		'Get-HPOVRemoteSupportEntitlementStatus'
		'Get-HPOVRemoteSupportPartner'
		'Get-HPOVRemoteSupportSetting'
		'Get-HPOVRemoteSyslog'
		'Get-HPOVReservedVlanRange'
		'Get-HPOVRole'
		'Get-HPOVSanManager'
		'Get-HPOVSanZone'
		'Get-HPOVSasInterconnectType'
		'Get-HPOVSasLogicalInterconnect'
		'Get-HPOVScmbCertificates'
		'Get-HPOVScope'
		'Get-HPOVServer'
		'Get-HPOVServerHardwareType'
		'Get-HPOVServerProfile'
		'Get-HPOVServerProfileConnectionList'
		'Get-HPOVServerProfileMessage'
		'Get-HPOVServerProfileTemplate'
		'Get-HPOVServiceAlert'
		'Get-HPOVSmtpConfig'
		'Get-HPOVSnmpReadCommunity'
		'Get-HPOVSnmpV3User'
		'Get-HPOVStoragePool'
		'Get-HPOVStorageSystem'
		'Get-HPOVStorageVolume'
		'Get-HPOVStorageVolumeSnapshot'
		'Get-HPOVStorageVolumeTemplate'
		'Get-HPOVStorageVolumeTemplatePolicy'
		'Get-HPOVSwitch'
		'Get-HPOVSwitchType'
		'Get-HPOVTask'
		'Get-HPOVUnmanagedDevice'
		'Get-HPOVUplinkSet'
		'Get-HPOVUser'
		'Get-HPOVVersion'
		'Get-HPOVXApiVersion'
		'Import-HPOVSSLCertificate'
		'Install-HPOVApplianceCertificate'
		'Install-HPOVLogicalInterconnectFirmware'
		'Install-HPOVUpdate'
		'Invoke-HPOVVcmMigration'
		'Invoke-HPOVWebBrowser'
		'Join-HPOVServerProfileToTemplate'
		'New-HPOVAddressPoolRange'
		'New-HPOVAddressPoolSubnet'
		'New-HPOVApplianceCsr'
		'New-HPOVApplianceSelfSignedCertificate'
		'New-HPOVApplianceTrapDestination'
		'New-HPOVBackup'
		'New-HPOVClusterProfile'
		'New-HPOVCustomBaseline'
		'New-HPOVDatacenter'
		'New-HPOVEnclosureGroup'
		'New-HPOVExternalRepository'
		'New-HPOVLdapDirectory'
		'New-HPOVLdapGroup'
		'New-HPOVLdapServer'
		'New-HPOVLicense'
		'New-HPOVLogicalEnclosure'
		'New-HPOVLogicalInterconnectGroup'
		'New-HPOVLogicalSwitch'
		'New-HPOVLogicalSwitchGroup'
		'New-HPOVNetwork'
		'New-HPOVNetworkSet'
		'New-HPOVOSDeploymentServer'
		'New-HPOVQosConfig'
		'New-HPOVQosTrafficClass'
		'New-HPOVRack'
		'New-HPOVRemoteSupportContact'
		'New-HPOVRemoteSupportPartner'
		'New-HPOVResource'
		'New-HPOVRestore'
		'New-HPOVScope'
		'New-HPOVServerProfile'
		'New-HPOVServerProfileAssign'
		'New-HPOVServerProfileAttachVolume'
		'New-HPOVServerProfileConnection'
		'New-HPOVServerProfileLogicalDisk'
		'New-HPOVServerProfileLogicalDiskController'
		'New-HPOVServerProfileTemplate'
		'New-HPOVSnmpConfiguration'
		'New-HPOVSnmpTrapDestination'
		'New-HPOVSnmpV3User'
		'New-HPOVStorageVolume'
		'New-HPOVStorageVolumeSnapShot'
		'New-HPOVStorageVolumeTemplate'
		'New-HPOVSupportDump'
		'New-HPOVUnmanagedDevice'
		'New-HPOVUplinkSet'
		'New-HPOVUser'
		'Ping-HPOVAddress'
		'Pop-HPOVAppliancePermission'
		'Push-HPOVAppliancePermission'
		'Remove-HPOVAddressPoolRange'
		'Remove-HPOVAddressPoolSubnet'
		'Remove-HPOVAlert'
		'Remove-HPOVApplianceProxy'
		'Remove-HPOVApplianceTrapDestination'
		'Remove-HPOVApplianceTrustedCertificate'
		'Remove-HPOVBaseline'
		'Remove-HPOVDatacenter'
		'Remove-HPOVEnclosure'
		'Remove-HPOVEnclosureGroup'
		'Remove-HPOVExternalRepository'
		'Remove-HPOVFabricManager'
		'Remove-HPOVHypervisorManager'
		'Remove-HPOVLdapDirectory'
		'Remove-HPOVLdapGroup'
		'Remove-HPOVLdapServer'
		'Remove-HPOVLicense'
		'Remove-HPOVLogicalEnclosure'
		'Remove-HPOVLogicalInterconnectGroup'
		'Remove-HPOVLogicalSwitch'
		'Remove-HPOVLogicalSwitchGroup'
		'Remove-HPOVNetwork'
		'Remove-HPOVNetworkSet'
		'Remove-HPOVOSDeploymentServer'
		'Remove-HPOVPEndingUpdate'
		'Remove-HPOVPowerDevice'
		'Remove-HPOVRack'
		'Remove-HPOVRackManager'
		'Remove-HPOVRackMember'
		'Remove-HPOVRemoteSupportContact'
		'Remove-HPOVRemoteSupportPartner'
		'Remove-HPOVResource'
		'Remove-HPOVResourceFromLabel'
		'Remove-HPOVResourceFromScope'
		'Remove-HPOVSanManager'
		'Remove-HPOVScmbCertificate'
		'Remove-HPOVScope'
		'Remove-HPOVServer'
		'Remove-HPOVServerProfile'
		'Remove-HPOVServerProfileTemplate'
		'Remove-HPOVSnmpV3User'
		'Remove-HPOVStandbyComposerNode'
		'Remove-HPOVStoragePool'
		'Remove-HPOVStorageSystem'
		'Remove-HPOVStorageVolume'
		'Remove-HPOVStorageVolumeSnapShot'
		'Remove-HPOVStorageVolumeTemplate'
		'Remove-HPOVUnmanagedDevice'
		'Remove-HPOVUser'
		'Reset-HPOVEnclosureDevice'
		'Restart-HPOVAppliance'
		'Restart-HPOVServer'
		'Restore-HPOVCustomBaseline'
		'Save-HPOVBackup'
		'Save-HPOVServerProfile'
		'Save-HPOVServerProfileTemplate'
		'Search-HPOVAssociations'
		'Search-HPOVIndex'
		'Send-HPOVRequest'
		'Set-HPOVAddressPoolSubnet'
		'Set-HPOVAlert'
		'Set-HPOVApplianceCurrentSecurityMode'
		'Set-HPOVApplianceDateTime'
		'Set-HPOVApplianceDefaultConnection'
		'Set-HPOVApplianceGlobalSetting'
		'Set-HPOVApplianceNetworkConfig'
		'Set-HPOVApplianceProxy'
		'Set-HPOVApplianceSecurityProtocol'
		'Set-HPOVApplianceTwoFactorAuthentication'
		'Set-HPOVAutomaticBackupConfig'
		'Set-HPOVDatacenter'
		'Set-HPOVDataCenterRemoteSupport'
		'Set-HPOVEnclosure'
		'Set-HPOVEnclosureActiveFLM'
		'Set-HPOVEnclosureGroup'
		'Set-HPOVEulaStatus'
		'Set-HPOVExternalRepository'
		'Set-HPOVHypervisorManager'
		'Set-HPOVInitialPassword'
		'Set-HPOVLdapDefaultDirectory'
		'Set-HPOVLdapGroupRole'
		'Set-HPOVLogicalEnclosure'
		'Set-HPOVLoginMessage'
		'Set-HPOVManagedSan'
		'Set-HPOVNetwork'
		'Set-HPOVNetworkSet'
		'Set-HPOVRackMemberLocation'
		'Set-HPOVRemoteSupport'
		'Set-HPOVRemoteSupportDataCollectionSchedule'
		'Set-HPOVRemoteSupportDefaultSite'
		'Set-HPOVRemoteSupportSetting'
		'Set-HPOVRemoteSyslog'
		'Set-HPOVReservedVlanRange'
		'Set-HPOVResource'
		'Set-HPOVSanManager'
		'Set-HPOVServerHardwareType'
		'Set-HPOVServerPower'
		'Set-HPOVServerProfile'
		'Set-HPOVServerProfileTemplate'
		'Set-HPOVSmtpConfig'
		'Set-HPOVSnmpReadCommunity'
		'Set-HPOVStoragePool'
		'Set-HPOVStorageVolume'
		'Set-HPOVStorageVolumeTemplate'
		'Set-HPOVStorageVolumeTemplatePolicy'
		'Set-HPOVUser'
		'Set-HPOVUserPassword'
		'Set-HPOVUserRole'
		'Show-HPOVActiveUser'
		'Show-HPOVApplianceSecurityModeCompatibilityReport'
		'Show-HPOVFirmwareReport'
		'Show-HPOVHypervisorCluster'
		'Show-HPOVLdapGroups'
		'Show-HPOVLogicalInterconnectMacTable'
		'Show-HPOVPortStatistics'
		'Show-HPOVSanEndpoint'
		'Show-HPOVUserSession'
		'Start-HPOVLibraryTrace'
		'Start-HPOVRemoteSupportCollection'
		'Start-HPOVServer'
		'Stop-HPOVAppliance'
		'Stop-HPOVLibraryTrace'
		'Stop-HPOVServer'
		'Test-HPOVEmailAlert'
		'Update-HPOVApplianceTrustedAuthorityCrl'
		'Update-HPOVEnclosure'
		'Update-HPOVExternalRepository'
		'Update-HPOVLogicalEnclosure'
		'Update-HPOVLogicalEnclosureFirmware'
		'Update-HPOVLogicalInterconnect'
		'Update-HPOVLogicalSwitch'
		'Update-HPOVRackManager'
		'Update-HPOVRemoteSupportEntitlement'
		'Update-HPOVSanManager'
		'Update-HPOVServer'
		'Update-HPOVServerHardwareLicenseIntent'
		'Update-HPOVServerProfile'
		'Update-HPOVStorageSystem'
		'Wait-HPOVApplianceStart'
		'Wait-HPOVTaskComplete'
		'Wait-HPOVTaskStart'
	)
	
	# Cmdlets to export from this module
	CmdletsToExport = ''
	
	# Variables to export from this module
	VariablesToExport = ''
	
	# Aliases to export from this module
	AliasesToExport    = @(
		'Add-HPOVSppFile'
		'Copy-HPOVProfile'
		'Get-HPOVProfile'
		'Get-HPOVProfileAssign'
		'Get-HPOVProfileConnectionList'
		'Get-HPOVServerHardwareTypes'
		'Get-HPOVSppFile'
		'New-HPOVAddressRange'
		'New-HPOVEnclosure'
		'New-HPOVLdap'
		'New-HPOVProfile'
		'New-HPOVProfileAttachVolume'
		'New-HPOVProfileConnection'
		'New-HPOVSanManager'
		'New-HPOVServer'
		'New-HPOVStoragePool'
		'New-HPOVStorageSystem'
		'Remove-HPOVLdap'
		'Remove-HPOVProfile'
		'Set-HPOVRole'
		'Show-HPOVBaselineRepositorySize'
		'sr'
		'Wait-HPOVTaskAccepted'
	)
	
	# List of all modules packaged with this module
	ModuleList = @()
	
	# List of all files packaged with this module
	FileList		   = @()
	
	HelpInfoURI = 'http://hewlettpackard.github.io/POSH-HPOneView/UpdateHelp'
	
	PrivateData	       = @{
		PSData = @{
			Tags = 'Hewlett', 'Packard', 'Enterprise', 'HPE', 'HPOneView', 'HPEOneView', 'HPESynergy';
			LicenseUri = 'https://github.com/HewlettPackard/POSH-HPOneView/blob/master/LICENSE';
			ProjectUri = 'http://hewlettpackard.github.io/POSH-HPOneView';
			IconUri = '';
			ReleaseNotes = 'Release 4.20.1971.1960
			
* Initial 4.20 release.'
			
		}
		
	}
}